name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@AR3Capital'      
      - run: npm install
      - run: npm run prisma:generate_my
      - run: npm run prisma:generate_mdb
      - run: npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_GIT_TOKEN}}
